version: '3'
services:
    express-typescript:
        build:
            context: .
            dockerfile: local.Dockerfile
        container_name: 'app-express-typescript'
        depends_on: -postgres
        volumes:
            - .:/usr/src/app/
        working_dir: /usr/src/app
        environment:
            - REDIS_QUEUE_HOST=redis
            - GOOGLE_ID=
            - GOOGLE_SECRET=
            - TWITTER_KEY=
            - TWITTER_SECRET=
        command: sh -c "npm install && npm run dev"
        ports:
            - 4040:4040
            - 5550:5550
    postgres:
        image: "postgres"
        ports:
            - "27017:27017"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=db
        expose:
            - 27017
        volumes:
            - ./db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
