version: '3'
services:
    express-typescript:
        build:
            context: .
            dockerfile: local.Dockerfile
        container_name: 'app-express-typescript'
        depends_on:
            # Our app does not work without our database
            # so this ensures our database is loaded first
            - postgres
        volumes:
            - .:/usr/src/app/
        working_dir: /usr/src/app
        environment:
            - GOOGLE_ID=
            - GOOGLE_SECRET=
            - TWITTER_KEY=
            - TWITTER_SECRET=
            - PORT=4040
            - POSTGRES_PORT=5433
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=db
            - POSTGRES_HOST=postgres
        command: sh -c "npm install && npm run dev"
        ports:
            - 4040:4040
            - 5550:5550
    postgres:
        image: "postgres"
        ports:
            - "5433:5433"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=db
        expose:
            - 5433
        volumes:
            - ./db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

    # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "aangeles@litystyles.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "16543:80"
        depends_on:
            - postgres
