# docker-compose.yml
version: "3"
services:
    express-typescript:
        build: .
        depends_on:
            - postgres
        working_dir: /usr/src/app
        environment:
            DATABASE_URL: postgres://user:pass@postgres:5432/db
            NODE_ENV: development
            PORT: 4040
        ports:
            - 4040:4040
        command: sh -c "npm install && npm run dev"
        volumes:
            - .:/usr/src/app/
            - /app/node_modules
    postgres:
        image: postgres:10.4
        ports:
            - "35431:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
        volumes:
            - ./db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
