# docker-compose.yml
version: "3"
services:
    postgres:
        image: postgres:10.4
        ports:
            - "35432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: db
        volumes:
            - ./db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped
